### ISSUE TITLE
Payment management upgrades

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codeconnect#22]
The current payment management system was built before our current approach to forms and objects was developed. Particularly, the current PaymentBB has member variables for each field on a Payment object. This is the old approach. Instead, now we only use a single member variable of type Payment named something like currentPayment and access the members directly from that object on all forms related to it.

Please complete the following:

1.  Combine PaymentManageBB and PaymentTypeManageBB into a single backing bean
2.  Upgrade the old design of both paymentManage.xhtml and paymentTypeManage.xhtml and their associated backing bean be wired directly to the business object (in this case either a Payment or a PaymentType object) and test

For testing, since occbeta does not currently allow back end access, you may want to move the xhtml pages into the public directory so you can actually test the pages.

**Comment by NADGIT** [comment]
I thought I would be finished with this by the end of my work period, but there were a lot of issues - for one, the payment integrator wasn't updated to reflect the changes done in the database. I also have to debug the payment management pages, since they're having issues. I'll probably finish them tomorrow morning, then return to this issue and close it.

**Comment by edarsow** [comment]
Great, Thanks Nathan!

**Comment by NADGIT** [comment]
I've finished all of my debugging. The Payment system now
1. uses only one backing bean
2. are connected to business objects as opposed to using fields built into the classes

I just have to pop the pages back into their old places, remove the public-facing buttons, and commit! Mind if I push?
