### ISSUE TITLE
Fee management upgrades

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codeconnect#23]
**Core goal:** Upgrade the Occupancy Fee management system to include modern methods of adding and updating objects using <p:dialog> tags and ajax calls.

**Background:** A Fee is an object that represents an amount due that has not yet been attached to either one of our two core objects: an OccPeriod and CECase. A FeeAssigned object contains a Fee along with associated fields for attaching that Fee to its business object.

We want users to be able to create a fee, say the $30 annual rental registry fee in Wilkins, using the fee manager. We also want to be able to edit this fee amount and commit these changes to the database.

In the original design, we thought that fees would only be associated with occupancy inspections and permits, we now know that there are fees associated with certain types of code violations, like "quality of life" ordinance violations that have an associated fee which is due to the muni even if compliance is achieved. (As opposed to a citation penalty which is hashed out in court.)

**Mini-project steps:**

1. Examine occInspectionFeeManage.xhtml and study its current structure. Note that there is a second form called ' <h:form id="poccInsFeeAddForm">'.
2.  Rename this file to be called just feeManage.xhtml (since we have fees for code enforcemetn too).
3. Embed the ' <h:form id="poccInsFeeAddForm">'. in a  <p:dialog> such that it can ride on top of the existing window when a Fee is added or updated.
4. Study a page like persons.xhtml which currently contains a form inside a dialog box. Note the use of the command button with its 'oncomplete' property set to show the dialog. Also note that the name used for the dialog is NOT the html ID field, it's the value of the dialog box's widgetVar property!

    <p:commandButton    id="new-person-cb"
    ajax="true" actionListener="#{personsBB.initiatePersonCreation}"
    oncomplete="PF('person-addupdate-dialog-var').show()"
    update="person-addupdate-form"
    value="Create new Person"
    rendered="#{sessionBean.facesUser.keyCard.hasMuniStaffPermissions}"
    icon="fa fa-plus"
    />

5. Refactor the payment manager and payment type manage page to use the dialogs just like this one.

**Comment by NADGIT** [comment]
I've finished  these tasks on my FeeUpgrade branch. It's pushed and ready for merging!

**Comment by edarsow** [comment]
And it's fantastic!
