### ISSUE TITLE
Create occupancy inspection feature

### ISSUE THREAD

**Issue by dpimpinella** [TechnologyRediscovery/codeconnect#8]
Occupancy inspections are to be conducted whenever a property changes owners or new tenants move in.

For those carrying out the inspection, the occupancy inspection feature will act as a checklist during the inspection process and reporting tool afterwards. It will need to be flexible enough to allow for the accurate inspection of properties of all types and sizes in many different municipalities.

**Comment by edarsow** [comment]
"topic" issue to be replaced with specific ones
